# Generated by Django 4.2.4 on 2023-12-13 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0002_remove_feedback_phone")]

    operations = [migrations.DeleteModel(name="Feedback")]
