# Generated by Django 4.2.4 on 2023-12-13 10:30

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("main", "0004_feedback")]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                upload_to="product_images/"
            ),
        )
    ]
