# Generated by Django 4.2.4 on 2023-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("main", "0006_defaultsubcategory")]

    operations = [
        migrations.AddField(
            model_name="defaultsubcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategory_images/"
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subcategory_images/"
            ),
        ),
    ]
