# Generated by Django 4.2.4 on 2024-01-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("main", "0008_defaultproduct_defualtproductoption")]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="enable_sending",
            field=models.BooleanField(default=False),
        )
    ]
